# Generated by Django 4.2.4 on 2023-11-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.TextField(null=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_co_no', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('fin_prdt_cd', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField()),
                ('cur_nm', models.TextField()),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.TextField(null=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_co_no', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('fin_prdt_cd', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
            ],
        ),
    ]
