# Generated by Django 4.2.4 on 2023-11-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='ttb',
            new_name='deal_bas_r',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='tts',
        ),
    ]
