# Generated by Django 4.2.4 on 2023-11-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
    ]
