# Generated by Django 4.2.4 on 2023-11-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_title_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
    ]
