# Generated by Django 4.2.4 on 2023-11-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='deposits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.depositoption'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='savings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.savingoption'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deposit_options',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.FinancialProduct', to='banks.depositoption'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saving_options',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.FinancialProduct', to='banks.savingoption'),
        ),
    ]
