# Generated by Django 4.2.4 on 2023-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='financial_product',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
