# Generated by Django 4.2.4 on 2023-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_age_alter_user_money_alter_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intr_rate_type_nm',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='join_way',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kor_co_nm',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.DeleteModel(
            name='MyPreference',
        ),
    ]
